import { test, expect } from './fixtures.js';
import { ARTICLES } from '../../../assets/javautils/knowledge/data.js';

test('knowledge home, local filters, version comparison and direct articles work without sending search data',async({page,context,appUrl},info)=>{
    const requests=[];
    context.on('request',r=>{if(/^https?:/.test(r.url()))requests.push({url:r.url(),body:r.postData(),method:r.method()});});
    await page.goto(appUrl+'/');
    await expect(page.locator('a[href$="jvmscope/tda.html"]').last()).toBeVisible();
    await page.getByRole('link',{name:/Explore eight Java knowledge articles/}).click();
    await expect(page).toHaveURL(appUrl+'/knowledge/index.html');
    await expect(page.locator('#knowledgeCount')).toHaveText('8 articles');
    await page.screenshot({path:info.outputPath('knowledge-index.png'),fullPage:true});
    await page.locator('#knowledgeSearch').fill('PRIVATE_SEARCH_SENTINEL');
    await expect(page.locator('#knowledgeCount')).toHaveText('0 articles');
    await page.locator('#knowledgeSearch').fill('pinning');
    await page.locator('#knowledgeVersion').selectOption('17');
    await expect(page.locator('#knowledgeArticles')).not.toContainText('Virtual threads, carriers and pinning');
    await page.locator('#knowledgeVersion').selectOption('27');
    await page.locator('#knowledgeTopic').selectOption('threads');
    await expect(page.locator('#knowledgeArticles a')).toHaveCount(1);
    await page.locator('#compareFrom').selectOption('24');
    await page.locator('#compareTo').selectOption('27');
    await expect(page.locator('#knowledgeComparison')).toContainText('Experimental; disabled by default');
    await expect(page.locator('#knowledgeComparison')).toContainText('Product; enabled by default');
    await page.locator('#compareFrom').selectOption('27');
    await expect(page.locator('#knowledgeComparison')).toContainText('does not mean the releases are equivalent');
    await page.locator('#knowledgeArticles a').click();
    await expect(page.locator('#knowledgeRoot h1')).toHaveText('Virtual threads, carriers and pinning');
    await page.reload();
    await expect(page.locator('#knowledgeRoot')).toContainText('Last source verification: 2026-10-05');
    await page.getByRole('link',{name:'← Knowledge base',exact:true}).click();
    for(const article of ARTICLES) {
        await page.goto(`${appUrl}/knowledge/${article.id}.html`);
        await expect(page.locator('#knowledgeRoot h1')).toHaveText(article.title);
        const icon=await page.locator('link[rel="icon"]').getAttribute('href');
        const iconUrl=new URL(icon,page.url());
        expect(iconUrl.href.startsWith(`${appUrl}/assets/`)).toBe(true);
        const iconResponse=await page.request.get(iconUrl.href);
        expect(iconResponse.status()).toBe(200);
        expect(iconResponse.headers()['content-type']).toContain('image/svg+xml');
        await expect(page.locator('#knowledgeRoot')).toContainText('A. Documented JVM capabilities');
        await expect(page.locator('#knowledgeRoot')).toContainText('B. What the selected collection actually contains');
        await expect(page.locator('#knowledgeRoot')).toContainText('C. What JvmScope has verified');
        await expect(page.locator('#knowledgeRoot')).toContainText('Primary sources');
        await page.locator('#articleVersion').selectOption('7');
        await expect(page.locator('#articleCoverage')).toContainText('3 TDA cases and 36 TLS cases');
        await page.locator('#knowledgeFormat').selectOption('json');
        await expect(page.locator('#formatEvidence')).toContainText('No CPU/allocation counters');
    }
    expect(requests.every(r=>new URL(r.url).origin===new URL(appUrl).origin && ['GET','HEAD'].includes(r.method) && r.body===null)).toBe(true);
    expect(JSON.stringify(requests)).not.toContain('PRIVATE_SEARCH_SENTINEL');
    expect(await page.evaluate(()=>JSON.stringify({local:Object.entries(localStorage),session:Object.entries(sessionStorage)}))).not.toContain('PRIVATE_SEARCH_SENTINEL');
});

test('knowledge compares the G1 default transition in 26 to 27 with its source and qualifications',async({page,appUrl})=>{
    await page.goto(`${appUrl}/knowledge/index.html`);
    await page.locator('#compareFrom').selectOption('26');
    await page.locator('#compareTo').selectOption('27');
    const row=page.locator('#knowledgeComparison tbody tr').filter({hasText:'G1 default collector'});
    await expect(row).toHaveCount(1);
    await expect(row).toContainText('Default on specified server configurations');
    await expect(row).toContainText('Default in all environments');
    await expect(row).toContainText('Explicit collector flags still override');
    await expect(row.locator('a[href="https://openjdk.org/jeps/523"]')).toHaveCount(1);
    await page.goto(`${appUrl}/knowledge/gc-memory.html?java=27`);
    await expect(page.locator('#articleCapabilities')).toContainText('Default in all environments');
    await expect(page.locator('#knowledgeRoot')).toContainText('JEP 523 makes G1 the upstream HotSpot default');
});

test('knowledge retains the selected Java version in article navigation, reload and return without sharing search text',async({page,appUrl})=>{
    await page.goto(`${appUrl}/knowledge/index.html`);
    await page.locator('#knowledgeVersion').selectOption('17');
    await page.locator('#knowledgeSearch').fill('PRIVATE_NAVIGATION_SENTINEL');
    expect(page.url()).not.toContain('PRIVATE_NAVIGATION_SENTINEL');
    await page.locator('#knowledgeSearch').fill('');
    const link=page.getByRole('link',{name:/Collect the right thread dump/});
    await expect(link).toHaveAttribute('href','./thread-dumps.html?java=17');
    await link.click();
    await expect(page.locator('#articleVersion')).toHaveValue('17');
    await page.reload();
    await expect(page.locator('#articleVersion')).toHaveValue('17');
    await page.locator('#articleVersion').selectOption('7');
    await expect(page).toHaveURL(`${appUrl}/knowledge/thread-dumps.html?java=7`);
    await page.reload();
    await expect(page.locator('#articleVersion')).toHaveValue('7');
    await page.getByRole('link',{name:'← Knowledge base',exact:true}).click();
    await expect(page.locator('#knowledgeVersion')).toHaveValue('7');
    await page.reload();
    await expect(page.locator('#knowledgeVersion')).toHaveValue('7');
    await page.locator('#knowledgeVersion').selectOption('');
    await expect(page).toHaveURL(`${appUrl}/knowledge/index.html`);
    await expect(page.getByRole('link',{name:/Collect the right thread dump/})).toHaveAttribute('href','./thread-dumps.html');
    await page.goto(`${appUrl}/knowledge/thread-dumps.html?java=${encodeURIComponent('<script>bad</script>')}`);
    await expect(page.locator('#articleVersion')).toHaveValue('27');
    await expect(page.locator('#knowledgeBack')).toHaveAttribute('href','./index.html');
});
